change old 'BSL' language to 'RSL'

diff --git a/git-securefetch b/git-securefetch
--- a/git-securefetch
+++ b/git-securefetch
@@ -4,219 +4,214 @@
 # Update this variable value with your GPG Key
 GPG_KEY=`git config user.signingkey`
 
-
-
 #************** Functions ***********************************
 
-#This function creates the bsl entries related to the fetch operation
-function update_bsl_fetch {
-		LAST_ENTRY=$(ls -1|grep -v 'bsl.tmp' |wc -l)
-		BSL=$(($LAST_ENTRY+1))
-		echo `od -A n -t u4 -N 4 /dev/urandom` > bsl.tmp
-		xxd -r -p bsl.tmp>$BSL
+#This function creates the rsl entries related to the fetch operation
+function update_rsl_fetch {
+  LAST_ENTRY=$(ls -1|grep -v 'rsl.tmp' |wc -l)
+  RSL=$(($LAST_ENTRY+1))
+  echo `od -A n -t u4 -N 4 /dev/urandom` > rsl.tmp
+  xxd -r -p rsl.tmp>$RSL
 
-		rm bsl.tmp
-		# Commit the new BSL
-		git add $BSL
-		git commit -S -qm "Adding the fetch entry at BSL"
-
-
+  rm rsl.tmp
+  # Commit the new RSL
+  git add $RSL
+  git commit -S -m "Adding the fetch entry at RSL"
 }
 
-#This function pushes the bsl branch to server
-function push_bsl {
-		git push -q --set-upstream origin bsl 2>/dev/null
-		#Checking the status of BSL Push
-		status=$?
-
+#This function pushes the rsl branch to server
+function push_rsl {
+  git push --set-upstream origin rsl 2>/dev/null
+  #Checking the status of RSL Push
+  status=$?
 }
 
 
-#This function intializes the bsl branch and creates bsl file intial entries
-function bsl_init {
+#This function intializes the rsl branch and creates rsl file intial entries
+function rsl_init {
 
-		#Set init variabe
-		init=1
-		git checkout -q --orphan bsl
-        git rm -qrf .
-        echo `od -A n -t d -N 4 /dev/urandom` > bsl.tmp
-        xxd -r -p bsl.tmp>1
+  #Set init variabe
+  init=1
+  git checkout -q --orphan rsl
+  git rm -qrf .
+  echo `od -A n -t d -N 4 /dev/urandom` > rsl.tmp
+  xxd -r -p rsl.tmp>1
 
-        rm bsl.tmp
-        # Commit the new BSL
-		git add 1
-		git commit -S -qm "Commiting the changes at BSL"
+  rm rsl.tmp
+  # Commit the new RSL
+  git add 1
+  git commit -S -qm "Commiting the changes at RSL"
 
 }
 
-# This function fetches the bsl and related branch
-function bsl_fetch {
+# This function fetches the rsl and related branch
+function rsl_fetch {
 
-	git fetch -q origin bsl
-    git checkout -q bsl
+  git fetch -q origin rsl
+    git checkout -q rsl
 
-    BSL=$(ls -1|grep -v 'bsl.tmp' |wc -l)
+    RSL=$(ls -1|grep -v 'rsl.tmp' |wc -l)
 
-	#finding the last verified push entry
-	while [ -f $BSL ]
-	do
-		if grep -q HEAD $BSL
-    	then
-    		#Update Last BSL push entry
-    		LAST_VERIFIED_PUSH_ENTRY=$BSL
-    		break
-    	else
-    		BSL=$(($BSL-1))
-    	fi
+  #finding the last verified push entry
+  while [ -f $RSL ]
+  do
+    if grep -q HEAD $RSL
+      then
+        #Update Last RSL push entry
+        LAST_VERIFIED_PUSH_ENTRY=$RSL
+        break
+      else
+        RSL=$(($RSL-1))
+      fi
     done
     git merge -q
 
     #Fetch the current branch from server
     git fetch -q origin $CURRENT_BRANCH 2>/dev/null
 
-    BSL=$(ls -1|grep -v 'bsl.tmp' |wc -l)
+    RSL=$(ls -1|grep -v 'rsl.tmp' |wc -l)
 
     #Finding out the last Push entry
-    while [ -f $BSL ]
+    while [ -f $RSL ]
     do
-    	if grep -q HEAD $BSL
-    	then
-    		#Get the branch head from the bsl
-    		BSL_BRANCH_HEAD=`cat $BSL |grep HEAD |tail -1|cut -d':' -f2`
-    		break
-    	else
-    		BSL=$(($BSL-1))
-    	fi
+      if grep -q HEAD $RSL
+      then
+        #Get the branch head from the rsl
+        RSL_BRANCH_HEAD=`cat $RSL |grep HEAD |tail -1|cut -d':' -f2`
+        break
+      else
+        RSL=$(($RSL-1))
+      fi
     done
 
     #Get the FETCH_HEAD
     cat .git/FETCH_HEAD
     FETCH_HEAD=`cat .git/FETCH_HEAD |grep $CURRENT_BRANCH |cut -f1`
 
-    #Verify the branch head in BSL matches with the FETCH_HEAD
-    if  [ "$BSL_BRANCH_HEAD" != "$FETCH_HEAD" ]
+    #Verify the branch head in RSL matches with the FETCH_HEAD
+    if  [ "$RSL_BRANCH_HEAD" != "$FETCH_HEAD" ]
     then
-    	fetch_status=1
+      fetch_status=1
     else
-    	fetch_status=0
+      fetch_status=0
     fi
 }
 
-#This function verifies the bsl file
-function bsl_verify {
+#This function verifies the rsl file
+function rsl_verify {
 
-		git checkout -q bsl
-		if git diff $BSL_PREV_HEAD HEAD --stat|grep -q 'deletion'
-		then
-		    echo "BSL file corrupted"
-		fi
+    git checkout -q rsl
+    if git diff $RSL_PREV_HEAD HEAD --stat|grep -q 'deletion'
+    then
+        echo "RSL file corrupted"
+    fi
 
-		#verify the signature on last enry
-		LAST_ENTRY=$(ls -lrt|wc -l)
-
-
-		#Computing Hash for previous entries
-		BSL=$(ls -1|grep -v 'bsl.tmp' |wc -l)
-
-		#Finding first push entry
-		for i in $(seq 1 $BSL)
-		do
-		    if grep -q HEAD $i
-    		then
-    			#Update Last BSL push entry
-    			FIRST_PUSH_ENTRY=$i
-    			break
-	    	else
-	    		BSL=$(($i+1))
-	    	fi
-	    done
-
-	    BSL=$(ls -1|grep -v 'bsl.tmp' |wc -l)
-		#finding the last push entry
-		while [ -f $BSL ]
-		do
-			if grep -q HEAD $BSL
-    		then
-    			#Update Last BSL push entry
-    			LAST_PUSH_ENTRY=$BSL
-    			break
-	    	else
-	    		BSL=$(($BSL-1))
-	    	fi
-	    done
+    #verify the signature on last enry
+    LAST_ENTRY=$(ls -lrt|wc -l)
 
 
-	    echo "******* Verifying the sign on last bsl entry *******"
+    #Computing Hash for previous entries
+    RSL=$(ls -1|grep -v 'rsl.tmp' |wc -l)
 
-	    if [ -f $LAST_PUSH_ENTRY ]
-	    then
-	    	gpg2 --default-key $GPG_KEY --verify $LAST_PUSH_ENTRY &> /dev/null
-	    	local status=$?
-			if [ $status -ne 0 ]
-			then
-				echo "Signature verification on last push entry is failed"
-			else
-				echo "Signature verification on last push entry is successful"
-			fi
-	    else
-	    	echo "There is no BSL push entry exist before. No need of signature verification"
-	    fi
+    #Finding first push entry
+    for i in $(seq 1 $RSL)
+    do
+        if grep -q HEAD $i
+        then
+          #Update Last RSL push entry
+          FIRST_PUSH_ENTRY=$i
+          break
+        else
+          RSL=$(($i+1))
+        fi
+      done
 
-	    echo "****************************************************"
+      RSL=$(ls -1|grep -v 'rsl.tmp' |wc -l)
+    #finding the last push entry
+    while [ -f $RSL ]
+    do
+      if grep -q HEAD $RSL
+        then
+          #Update Last RSL push entry
+          LAST_PUSH_ENTRY=$RSL
+          break
+        else
+          RSL=$(($RSL-1))
+        fi
+      done
 
-	    echo "******* Verifying the hash on new bsl push entries *******"
-	    #Hash Verification
 
-	    VERIFY=1
-	    while [ $VERIFY -eq 1 ]
-	    do
-			BSL=$(($LAST_PUSH_ENTRY-1))
-			while [ -f $BSL ]
-			do
-				if grep -q HEAD $BSL
-	    		then
-	    			#Update Last BSL push entry
-	    			LAST_PUSH_ENTRY2=$BSL
-	    			break
-		    	else
-		    		BSL=$(($BSL-1))
-		    	fi
-		    done
+      echo "******* Verifying the sign on last rsl entry *******"
 
-			if [ -f $LAST_PUSH_ENTRY2 ]
-			then
-			    for i in $(seq $LAST_PUSH_ENTRY2 $(($LAST_PUSH_ENTRY-1)))
-			    do
-			    	cat $i >>hash_file.tmp
-			    done
-			else
-			    for i in $(seq 1 $(($LAST_PUSH_ENTRY-1)))
-			    do
-			    	cat $i >>hash_file.tmp
-			    done
-			fi
+      if [ -f $LAST_PUSH_ENTRY ]
+      then
+        gpg2 --default-key $GPG_KEY --verify $LAST_PUSH_ENTRY &> /dev/null
+        local status=$?
+      if [ $status -ne 0 ]
+      then
+        echo "Signature verification on last push entry is failed"
+      else
+        echo "Signature verification on last push entry is successful"
+      fi
+      else
+        echo "There is no RSL push entry exist before. No need of signature verification"
+      fi
 
-			HASH_1=`cat $LAST_PUSH_ENTRY|grep 'PREV_HASH:'|cut -d':' -f2`
-			HASH_2=`cat hash_file.tmp|shasum|cut -d' ' -f1`
+      echo "****************************************************"
 
-			if [[ "$HASH_2" != "$HASH_1" && ! -z "$HASH_1" ]]
-			then
-				    echo "Hash verfication on the following entry failed"
-				    echo "HASH_1:"$HASH_1 "  HASH_2":$HASH_2
-				    echo `cat hash_file.tmp`
-				    exit 1
-			else
-				   	echo "Hash verification successful "
-			fi
-			rm hash_file.tmp
+      echo "******* Verifying the hash on new rsl push entries *******"
+      #Hash Verification
 
-			if [[  $LAST_PUSH_ENTRY -eq $LAST_VERIFIED_PUSH_ENTRY || $LAST_PUSH_ENTRY -eq $FIRST_PUSH_ENTRY || -z $LAST_PUSH_ENTRY ]]
-			then
-			 		VERIFY=0
-			fi
-			LAST_PUSH_ENTRY=$LAST_PUSH_ENTRY2
-			LAST_PUSH_ENTRY2=0
-		done
+      VERIFY=1
+      while [ $VERIFY -eq 1 ]
+      do
+      RSL=$(($LAST_PUSH_ENTRY-1))
+      while [ -f $RSL ]
+      do
+        if grep -q HEAD $RSL
+          then
+            #Update Last RSL push entry
+            LAST_PUSH_ENTRY2=$RSL
+            break
+          else
+            RSL=$(($RSL-1))
+          fi
+        done
+
+      if [ -f $LAST_PUSH_ENTRY2 ]
+      then
+          for i in $(seq $LAST_PUSH_ENTRY2 $(($LAST_PUSH_ENTRY-1)))
+          do
+            cat $i >>hash_file.tmp
+          done
+      else
+          for i in $(seq 1 $(($LAST_PUSH_ENTRY-1)))
+          do
+            cat $i >>hash_file.tmp
+          done
+      fi
+
+      HASH_1=`cat $LAST_PUSH_ENTRY|grep 'PREV_HASH:'|cut -d':' -f2`
+      HASH_2=`cat hash_file.tmp|shasum|cut -d' ' -f1`
+
+      if [[ "$HASH_2" != "$HASH_1" && ! -z "$HASH_1" ]]
+      then
+            echo "Hash verfication on the following entry failed"
+            echo "HASH_1:"$HASH_1 "  HASH_2":$HASH_2
+            echo `cat hash_file.tmp`
+            exit 1
+      else
+            echo "Hash verification successful "
+      fi
+      rm hash_file.tmp
+
+      if [[  $LAST_PUSH_ENTRY -eq $LAST_VERIFIED_PUSH_ENTRY || $LAST_PUSH_ENTRY -eq $FIRST_PUSH_ENTRY || -z $LAST_PUSH_ENTRY ]]
+      then
+          VERIFY=0
+      fi
+      LAST_PUSH_ENTRY=$LAST_PUSH_ENTRY2
+      LAST_PUSH_ENTRY2=0
+    done
 
 }
 
@@ -226,67 +221,67 @@ function bsl_verify {
 #Get Current Brach
 CURRENT_BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
 
-#check if we are pushing bsl branch
-if [ "$CURRENT_BRANCH" == "bsl" ]
+#check if we are pushing rsl branch
+if [ "$CURRENT_BRANCH" == "rsl" ]
 then
     exit 0
 fi
 
 status=1
-# Repeat the following steps until bsl push is successful
+# Repeat the following steps until rsl push is successful
 while [ $status -ne 0 ]
 do
-	#Fetch BSL
-	if  [[ $(git branch -a |grep 'remotes/origin/bsl') ]]
-	then
+  #Fetch RSL
+  if  [[ $(git branch -a |grep 'remotes/origin/rsl') ]]
+  then
 
-		fetch_status=1
-		while [ $fetch_status -ne 0 ]
-		do
-			#fetch the BSL branch and current branch
-			echo "Fetching the bsl ..."
-			bsl_fetch
-		done
+    fetch_status=1
+    while [ $fetch_status -ne 0 ]
+    do
+      #fetch the RSL branch and current branch
+      echo "Fetching the rsl ..."
+      rsl_fetch
+    done
 
-		# Update the BSL file
-		echo "Updating the bsl ..."
-		update_bsl_fetch
-	else
-		# BSL branch Intialization
-		echo "Intializing the bsl ..."
-		bsl_init
+    # Update the RSL file
+    echo "Updating the rsl ..."
+    update_rsl_fetch
+  else
+    # RSL branch Intialization
+    echo "Intializing the rsl ..."
+    rsl_init
 
-	fi
+  fi
 
-	#Pushing the BSL
-	echo "Pushing the bsl ... "
-	push_bsl
-	if [ $status -ne 0 ]
-	then
-		echo "bsl push failed !!"
-		git reset --hard origin/bsl
-	fi
+  #Pushing the RSL
+  echo "Pushing the rsl ... "
+  push_rsl
+  if [ $status -ne 0 ]
+  then
+    echo "rsl push failed !!"
+    git reset --hard origin/rsl
+  fi
 done
 
-BSL=$(ls -1|grep -v 'bsl.tmp' |wc -l)
+RSL=$(ls -1|grep -v 'rsl.tmp' |wc -l)
 #finding the last push entry
-while [ -f $BSL ]
+while [ -f $RSL ]
 do
-	if grep -q HEAD $BSL
+  if grep -q HEAD $RSL
     then
-    	#Update Last BSL push entry
-    	LAST_PUSH_ENTRY=$BSL
-    	break
-	else
-	    BSL=$(($BSL-1))
-	fi
+      #Update Last RSL push entry
+      LAST_PUSH_ENTRY=$RSL
+      break
+  else
+      RSL=$(($RSL-1))
+  fi
 done
 
 if [[ $LAST_VERIFIED_PUSH_ENTRY -eq 1 || -z "$LAST_VERIFIED_PUSH_ENTRY" || $LAST_PUSH_ENTRY -eq $LAST_VERIFIED_PUSH_ENTRY ]]
 then
-	echo "No verification required"
+  echo "No verification required"
 else
-	bsl_verify
+  rsl_verify
 fi
 
 #Switch back to current branch
diff --git a/git-securepush b/git-securepush
--- a/git-securepush
+++ b/git-securepush
@@ -7,130 +7,130 @@ GPG_KEY=`git config user.signingkey`
 
 #************** Functions ***********************************
 
-#This function creates the bsl entries related to the push operation
-function update_bsl_push {
+#This function creates the rsl entries related to the push operation
+function update_rsl_push {
 
-	commits=`git log @{u}.. --pretty=format:"%H" 2>/dev/null || git rev-list $CURRENT_BRANCH`
-	git checkout -q bsl
+  commits=`git log @{u}.. --pretty=format:"%H" 2>/dev/null || git rev-list $CURRENT_BRANCH`
+  git checkout -q rsl
 
-	#Computing Hash for previous entries
-	BSL=$(ls -1|grep -v 'bsl.tmp' |wc -l)
+  #Computing Hash for previous entries
+  RSL=$(ls -1|grep -v 'rsl.tmp' |wc -l)
 
-	#finding the last push entry
-	while [ -f $BSL ]
-	do
-		if grep -q HEAD $BSL
-    	then
-    		#Update Last BSL push entry
-    		LAST_PUSH_ENTRY=$BSL
-    		break
-    	else
-    		BSL=$(($BSL-1))
-    	fi
+  #finding the last push entry
+  while [ -f $RSL ]
+  do
+    if grep -q HEAD $RSL
+      then
+        #Update Last RSL push entry
+        LAST_PUSH_ENTRY=$RSL
+        break
+      else
+        RSL=$(($RSL-1))
+      fi
     done
 
     #Caluculating the HASH
-    LAST_ENTRY=$(ls -1|grep -v 'bsl.tmp' |wc -l)
+    LAST_ENTRY=$(ls -1|grep -v 'rsl.tmp' |wc -l)
     if [ -f $LAST_PUSH_ENTRY ]
     then
-    	for i in $(seq $LAST_PUSH_ENTRY $LAST_ENTRY)
-    	do
-    		cat $i >>hash_file.tmp
-    	done
+      for i in $(seq $LAST_PUSH_ENTRY $LAST_ENTRY)
+      do
+        cat $i >>hash_file.tmp
+      done
     else
-    	for i in $(seq 1 $LAST_ENTRY)
-    	do
-    		cat $i >>hash_file.tmp
-    	done
+      for i in $(seq 1 $LAST_ENTRY)
+      do
+        cat $i >>hash_file.tmp
+      done
     fi
 
-	HASH=`cat hash_file.tmp|shasum | cut -d' ' -f1`
-	rm hash_file.tmp
+  HASH=`cat hash_file.tmp|shasum | cut -d' ' -f1`
+  rm hash_file.tmp
 
-	#Updte bsl
-	echo "Related Commits" >bsl.tmp
-	echo $commits >>bsl.tmp
-	echo "Branch:"$CURRENT_BRANCH >>bsl.tmp
-	HEAD_HASH=`git rev-parse $CURRENT_BRANCH`
-	echo "HEAD":$HEAD_HASH >>bsl.tmp
-	echo "PREV_HASH:"$HASH >>bsl.tmp
+  #Updte rsl
+  echo "Related Commits" >rsl.tmp
+  echo $commits >>rsl.tmp
+  echo "Branch:"$CURRENT_BRANCH >>rsl.tmp
+  HEAD_HASH=`git rev-parse $CURRENT_BRANCH`
+  echo "HEAD":$HEAD_HASH >>rsl.tmp
+  echo "PREV_HASH:"$HASH >>rsl.tmp
 }
 
-#This function creates the bsl entries related to the fetch operation
-function update_bsl_fetch {
+#This function creates the rsl entries related to the fetch operation
+function update_rsl_fetch {
 
-		LAST_ENTRY=$(ls -1|grep -v 'bsl.tmp' |wc -l)
-		BSL=$(($LAST_ENTRY+1))
-		echo `od -A n -t d -N 4 /dev/urandom` >$BSL
+    LAST_ENTRY=$(ls -1|grep -v 'rsl.tmp' |wc -l)
+    RSL=$(($LAST_ENTRY+1))
+    echo `od -A n -t d -N 4 /dev/urandom` >$RSL
 
-		git add $BSL
-		git commit -S -qm "Adding the fetch entry at BSL"
+    git add $RSL
+    git commit -S -qm "Adding the fetch entry at RSL"
 }
 
-#This function intializes the bsl branch and creates bsl file intial entries
-function bsl_init {
+#This function intializes the rsl branch and creates rsl file intial entries
+function rsl_init {
 
-		#Set init variabe
-		init=1
-		commits=`git rev-list $CURRENT_BRANCH`
-		git checkout -q --orphan bsl
+    #Set init variabe
+    init=1
+    commits=`git rev-list $CURRENT_BRANCH`
+    git checkout -q --orphan rsl
         git rm -qrf .
-        echo "Related Commits" >bsl.tmp
-		echo $commits >>bsl.tmp
-        echo "Branch:"$CURRENT_BRANCH >>bsl.tmp
+        echo "Related Commits" >rsl.tmp
+    echo $commits >>rsl.tmp
+        echo "Branch:"$CURRENT_BRANCH >>rsl.tmp
         HEAD_HASH=`git rev-parse $CURRENT_BRANCH`
-		echo "HEAD":$HEAD_HASH >>bsl.tmp
-		echo "PREV_HASH:"$HASH >>bsl.tmp
+    echo "HEAD":$HEAD_HASH >>rsl.tmp
+    echo "PREV_HASH:"$HASH >>rsl.tmp
 }
 
 
-#This function fetches the newer version of bsl
-function bsl_fetch {
+#This function fetches the newer version of rsl
+function rsl_fetch {
 
-	git fetch -q origin bsl
-    git checkout -q bsl
+  git fetch -q origin rsl
+    git checkout -q rsl
 
-    BSL=$(ls -1|grep -v 'bsl.tmp' |wc -l)
+    RSL=$(ls -1|grep -v 'rsl.tmp' |wc -l)
 
-	#finding the last verified push entry
-	while [ -f $BSL ]
-	do
-		if grep -q HEAD $BSL
-    	then
-    		#Update Last BSL push entry
-    		LAST_VERIFIED_PUSH_ENTRY=$BSL
-    		break
-    	else
-    		BSL=$(($BSL-1))
-    	fi
+  #finding the last verified push entry
+  while [ -f $RSL ]
+  do
+    if grep -q HEAD $RSL
+      then
+        #Update Last RSL push entry
+        LAST_VERIFIED_PUSH_ENTRY=$RSL
+        break
+      else
+        RSL=$(($RSL-1))
+      fi
     done
 
     git merge -q
 }
 
-# This function will sign the bsl entries and commits the changes
-function sign_bsl {
+# This function will sign the rsl entries and commits the changes
+function sign_rsl {
 
-		LAST_ENTRY=$(ls -1|grep -v 'bsl.tmp' |wc -l)
-		BSL=$(($LAST_ENTRY+1))
-		#Signthe bsl
-		cat bsl.tmp |gpg --default-key $GPG_KEY --clearsign >$BSL
+    LAST_ENTRY=$(ls -1|grep -v 'rsl.tmp' |wc -l)
+    RSL=$(($LAST_ENTRY+1))
+    #Signthe rsl
+    cat rsl.tmp |gpg --default-key $GPG_KEY --clearsign >$RSL
 
-		#Remove temp file
-		rm bsl.tmp
+    #Remove temp file
+    rm rsl.tmp
 
-		# Commit the new BSL
-		git add $BSL
-		git commit -S -qm "Adding the push entry at BSL"
+    # Commit the new RSL
+    git add $RSL
+    git commit -S -qm "Adding the push entry at RSL"
 }
 
-#This function pushes the bsl branch to server
-function push_bsl {
+#This function pushes the rsl branch to server
+function push_rsl {
 
-		git push -q --set-upstream origin bsl 2>/dev/null
+    git push -q --set-upstream origin rsl 2>/dev/null
 
-		#Checking the status of BSL Push
-		status=$?
+    #Checking the status of RSL Push
+    status=$?
 
 }
 
@@ -138,129 +138,129 @@ function push_bsl {
 
 function push_branch {
 
-	git checkout -q $CURRENT_BRANCH
-	git push -q --set-upstream origin $CURRENT_BRANCH
+  git checkout -q $CURRENT_BRANCH
+  git push -q --set-upstream origin $CURRENT_BRANCH
 
 }
 
 
-#This function verifies the bsl file
-function bsl_verify {
+#This function verifies the rsl file
+function rsl_verify {
 
-		git checkout -q bsl
-		if git diff $BSL_PREV_HEAD HEAD --stat|grep -q 'deletion'
-		then
-		    echo "BSL file corrupted"
-		fi
+    git checkout -q rsl
+    if git diff $RSL_PREV_HEAD HEAD --stat|grep -q 'deletion'
+    then
+        echo "RSL file corrupted"
+    fi
 
-		#verify the signature on last enry
-		LAST_ENTRY=$(ls -lrt|wc -l)
-
-
+    #verify the signature on last enry
+    LAST_ENTRY=$(ls -lrt|wc -l)
 
 
-		#Computing Hash for previous entries
-		BSL=$(ls -1|grep -v 'bsl.tmp' |wc -l)
 
-		#Finding first push entry
-		for i in $(seq 1 $BSL)
-		do
-		    if grep -q HEAD $i
-    		then
-    			#Update Last BSL push entry
-    			FIRST_PUSH_ENTRY=$i
-    			break
-	    	else
-	    		BSL=$(($i+1))
-	    	fi
-	    done
 
-	    BSL=$(ls -1|grep -v 'bsl.tmp' |wc -l)
-		#finding the last push entry
-		while [ -f $BSL ]
-		do
-			if grep -q HEAD $BSL
-    		then
-    			#Update Last BSL push entry
-    			LAST_PUSH_ENTRY=$BSL
-    			break
-	    	else
-	    		BSL=$(($BSL-1))
-	    	fi
-	    done
-	    echo "******* Verifying the sign on last bsl entry *******"
+    #Computing Hash for previous entries
+    RSL=$(ls -1|grep -v 'rsl.tmp' |wc -l)
 
-	    if [ -f $LAST_PUSH_ENTRY ]
-	    then
-	    	gpg2 --default-key $GPG_KEY --verify $LAST_PUSH_ENTRY &> /dev/null
-	    	local status=$?
-			if [ $status -ne 0 ]
-			then
-				echo "Signature verification on last push entry is failed"
-			else
-				echo "Signature verification on last push entry is successful"
-			fi
-	    else
-	    	echo "There is no BSL push entry exist before. No need of signature verification"
-	    fi
+    #Finding first push entry
+    for i in $(seq 1 $RSL)
+    do
+        if grep -q HEAD $i
+        then
+          #Update Last RSL push entry
+          FIRST_PUSH_ENTRY=$i
+          break
+        else
+          RSL=$(($i+1))
+        fi
+      done
 
-	    echo "****************************************************"
+      RSL=$(ls -1|grep -v 'rsl.tmp' |wc -l)
+    #finding the last push entry
+    while [ -f $RSL ]
+    do
+      if grep -q HEAD $RSL
+        then
+          #Update Last RSL push entry
+          LAST_PUSH_ENTRY=$RSL
+          break
+        else
+          RSL=$(($RSL-1))
+        fi
+      done
+      echo "******* Verifying the sign on last rsl entry *******"
 
-	    echo "******* Verifying the hash on new bsl push entries *******"
-	    #Hash Verification
+      if [ -f $LAST_PUSH_ENTRY ]
+      then
+        gpg2 --default-key $GPG_KEY --verify $LAST_PUSH_ENTRY &> /dev/null
+        local status=$?
+      if [ $status -ne 0 ]
+      then
+        echo "Signature verification on last push entry is failed"
+      else
+        echo "Signature verification on last push entry is successful"
+      fi
+      else
+        echo "There is no RSL push entry exist before. No need of signature verification"
+      fi
 
-	    VERIFY=1
-	    while [ $VERIFY -eq 1 ]
-	    do
-			BSL=$(($LAST_PUSH_ENTRY-1))
-			while [ -f $BSL ]
-			do
-				if grep -q HEAD $BSL
-	    		then
-	    			#Update Last BSL push entry
-	    			LAST_PUSH_ENTRY2=$BSL
-	    			break
-		    	else
-		    		BSL=$(($BSL-1))
-		    	fi
-		    done
+      echo "****************************************************"
 
-			if [ -f $LAST_PUSH_ENTRY2 ]
-			then
-			    for i in $(seq $LAST_PUSH_ENTRY2 $(($LAST_PUSH_ENTRY-1)))
-			    do
-			    	cat $i >>hash_file.tmp
-			    done
-			else
-			    for i in $(seq 1 $(($LAST_PUSH_ENTRY-1)))
-			    do
-			    	cat $i >>hash_file.tmp
-			    done
-			fi
+      echo "******* Verifying the hash on new rsl push entries *******"
+      #Hash Verification
 
-			HASH_1=`cat $LAST_PUSH_ENTRY|grep 'PREV_HASH:'|cut -d':' -f2`
-			HASH_2=`cat hash_file.tmp|shasum|cut -d' ' -f1`
+      VERIFY=1
+      while [ $VERIFY -eq 1 ]
+      do
+      RSL=$(($LAST_PUSH_ENTRY-1))
+      while [ -f $RSL ]
+      do
+        if grep -q HEAD $RSL
+          then
+            #Update Last RSL push entry
+            LAST_PUSH_ENTRY2=$RSL
+            break
+          else
+            RSL=$(($RSL-1))
+          fi
+        done
 
-			if [[ "$HASH_2" != "$HASH_1" && ! -z "$HASH_1" ]]
-			then
-				    echo "Hash verfication on the following entry failed"
-				    echo "HASH_1:"$HASH_1 "  HASH_2":$HASH_2
-				    echo `cat hash_file.tmp`
-				    exit 1
-			else
-				   	echo "Hash verification successful "
-			fi
-			rm hash_file.tmp
+      if [ -f $LAST_PUSH_ENTRY2 ]
+      then
+          for i in $(seq $LAST_PUSH_ENTRY2 $(($LAST_PUSH_ENTRY-1)))
+          do
+            cat $i >>hash_file.tmp
+          done
+      else
+          for i in $(seq 1 $(($LAST_PUSH_ENTRY-1)))
+          do
+            cat $i >>hash_file.tmp
+          done
+      fi
 
-			if [[ $LAST_PUSH_ENTRY -eq $LAST_VERIFIED_PUSH_ENTRY || $LAST_PUSH_ENTRY -eq $FIRST_PUSH_ENTRY || -z $LAST_PUSH_ENTRY ]]
-			then
-				VERIFY=0
-			fi
+      HASH_1=`cat $LAST_PUSH_ENTRY|grep 'PREV_HASH:'|cut -d':' -f2`
+      HASH_2=`cat hash_file.tmp|shasum|cut -d' ' -f1`
 
-			LAST_PUSH_ENTRY=$LAST_PUSH_ENTRY2
-			LAST_PUSH_ENTRY2=0
+      if [[ "$HASH_2" != "$HASH_1" && ! -z "$HASH_1" ]]
+      then
+            echo "Hash verfication on the following entry failed"
+            echo "HASH_1:"$HASH_1 "  HASH_2":$HASH_2
+            echo `cat hash_file.tmp`
+            exit 1
+      else
+            echo "Hash verification successful "
+      fi
+      rm hash_file.tmp
 
-		done
+      if [[ $LAST_PUSH_ENTRY -eq $LAST_VERIFIED_PUSH_ENTRY || $LAST_PUSH_ENTRY -eq $FIRST_PUSH_ENTRY || -z $LAST_PUSH_ENTRY ]]
+      then
+        VERIFY=0
+      fi
+
+      LAST_PUSH_ENTRY=$LAST_PUSH_ENTRY2
+      LAST_PUSH_ENTRY2=0
+
+    done
 
 }
 
@@ -272,67 +272,67 @@ function bsl_verify {
 #Get Current Brach
 CURRENT_BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
 
-#check if we are pushing bsl branch
-if [ "$CURRENT_BRANCH" == "bsl" ]
+#check if we are pushing rsl branch
+if [ "$CURRENT_BRANCH" == "rsl" ]
 then
     exit 0
 fi
 
 
-#Update BSL
-if  [[ $(git branch -a |grep 'remotes/origin/bsl') ]]
+#Update RSL
+if  [[ $(git branch -a |grep 'remotes/origin/rsl') ]]
 then
-	echo "Updating the bsl ..."
-	update_bsl_push
+  echo "Updating the rsl ..."
+  update_rsl_push
 else
-	# BSL branch Intialization
-	echo "Intializing the bsl ..."
-	bsl_init
+  # RSL branch Intialization
+  echo "Intializing the rsl ..."
+  rsl_init
 fi
-#Signing the bsl
-echo "Signing and Commiting the bsl ..."
-sign_bsl
+#Signing the rsl
+echo "Signing and Commiting the rsl ..."
+sign_rsl
 
-#Push BSL
-echo "Pushing the bsl ... "
-push_bsl
+#Push RSL
+echo "Pushing the rsl ... "
+push_rsl
 while [ $status -ne 0 ]
 do
-	echo "bsl push failed !!"
-	echo "Fetching the bsl from server ..."
-	#reset the bsl branch
-	git reset --hard origin/bsl
-	bsl_fetch
-	bsl_verify
+  echo "rsl push failed !!"
+  echo "Fetching the rsl from server ..."
+  #reset the rsl branch
+  git reset --hard origin/rsl
+  rsl_fetch
+  rsl_verify
 
-	BSL=$(ls -1|grep -v 'bsl.tmp' |wc -l)
-	#finding the last push entry
-	while [ -f $BSL ]
-	do
-		if grep -q HEAD $BSL
-    	then
-    		#Update Last BSL push entry
-    		LAST_PUSH_ENTRY=$BSL
-    		break
-    	else
-    		BSL=$(($BSL-1))
-    	fi
+  RSL=$(ls -1|grep -v 'rsl.tmp' |wc -l)
+  #finding the last push entry
+  while [ -f $RSL ]
+  do
+    if grep -q HEAD $RSL
+      then
+        #Update Last RSL push entry
+        LAST_PUSH_ENTRY=$RSL
+        break
+      else
+        RSL=$(($RSL-1))
+      fi
     done
-	BSL_BRANCH_HEAD=`cat $LAST_PUSH_ENTRY |grep HEAD |tail -1|cut -d':' -f2`
-	#Verify the branch can be pushed to remote
-	if [[ $(git rev-list $CURRENT_BRANCH|grep $BSL_BRANCH_HEAD) ]]
-	then
-		echo "Updating the bsl with push entry"
-		update_bsl_push
-		echo "Signing the bsl"
-		sign_bsl
-		echo "Pushing the bsl"
-		push_bsl
-	else
-		echo $CURRENT_BRANCH "Cann't be pushed to remote. Please fetch an merge the changes then retry the fetch"
-		git checkout -q $CURRENT_BRANCH
-		exit 1
-	fi
+  RSL_BRANCH_HEAD=`cat $LAST_PUSH_ENTRY |grep HEAD |tail -1|cut -d':' -f2`
+  #Verify the branch can be pushed to remote
+  if [[ $(git rev-list $CURRENT_BRANCH|grep $RSL_BRANCH_HEAD) ]]
+  then
+    echo "Updating the rsl with push entry"
+    update_rsl_push
+    echo "Signing the rsl"
+    sign_rsl
+    echo "Pushing the rsl"
+    push_rsl
+  else
+    echo $CURRENT_BRANCH "Cann't be pushed to remote. Please fetch an merge the changes then retry the fetch"
+    git checkout -q $CURRENT_BRANCH
+    exit 1
+  fi
 done
 
 
