Add Jenkinsfile
Prior to this commit, we did not have a Jenkinsfile, so we could
not see if the tests actually work on Jenkins.  This commit add
the Jenkinsfile so that we can test the scripts on Jenkins

diff --git a/git-promote b/git-promote
--- a/git-promote
+++ b/git-promote
@@ -5,6 +5,15 @@ REQUESTING=$1
 INDEX=`expr index "$REQUESTING" -`
 TAG=${REQUESTING:0:INDEX-1}
 
+CURRENT_BRANCH="$(git symbolic-ref --short HEAD)"
+
+STASH_OUTPUT="$(git stash push)"
+if [ $? != 0 ]; then
+	echo "ERROR:"
+	echo "$STASH_OUTPUT"
+	exit 1
+fi
+
 FETCH_OUTPUT="$(git fetch)"
 if [ $? != 0 ]; then
 	echo "ERROR:"
@@ -45,6 +54,15 @@ if [ $? != 0 ]; then
 	echo "ERROR:"
 	echo "TAG_OUTPUT"
 	exit 1
+fi
+
+if [ "$STASH_OUTPUT" != "No local changes to save" ]; then
+	POP_STASH="$(git stash pop)"
+	if [ $? != 0 ]; then
+		echo "ERROR:"
+		echo "$POP_STASH"
+		exit 1
+	fi
 fi
 
 exit 0
