Add error handling and tests

diff --git a/git-promote b/git-promote
--- a/git-promote
+++ b/git-promote
@@ -8,6 +8,20 @@ RELEASE_TAG=${PRERELEASE_TAG:0:INDEX-1}
 
 CURRENT_BRANCH="$(git symbolic-ref --short HEAD)"
 
+STASH_OUTPUT=''
+
+function unstash_changes()
+{
+	if [ "$STASH_OUTPUT" != "No local changes to save" ]; then
+		POP_STASH="$(git stash pop)"
+		if [ $? != 0 ]; then
+			echo "ERROR:"
+			echo "$POP_STASH"
+			exit 8
+		fi
+	fi
+}
+
 STASH_OUTPUT="$(git stash save)"
 if [ $? != 0 ]; then
 	echo "ERROR:"
@@ -19,51 +33,50 @@ FETCH_OUTPUT="$(git fetch -q --tags)"
 if [ $? != 0 ]; then
 	echo "ERROR:"
 	echo "$FETCH_OUTPUT"
-	exit 1
+	unstash_changes
+	exit 2
 fi
 
 CHECKOUT_OUTPUT="$(git checkout -q $TARGET_BRANCH)"
 if [ $? != 0 ]; then
 	echo "ERROR:"
-	echo "$CHECKOUT_OUTPUT"
-	exit 1
+	echo "Your target branch does not appear to exist"
+	unstash_changes
+	exit 3
 fi
 
 FF_MASTER_OUTPUT="$(git merge -q --ff-only origin/$TARGET_BRANCH)"
 if [ $? != 0 ]; then
 	echo "ERROR:"
 	echo "$FF_MASTER_OUTPUT"
-	exit 1
+	unstash_changes
+	exit 4
 fi
 
 MERGE_OUTPUT="$(git merge -q -S --no-ff $PRERELEASE_TAG)"
 if [ $? != 0 ]; then
 	echo "ERROR:"
 	echo "$MERGE_OUTPUT"
-	exit 1
+	unstash_changes
+	exit 5
 fi
 
 TAG_OUTPUT="$(git tag -s $RELEASE_TAG -m $RELEASE_TAG)"
 if [ $? != 0 ]; then
 	echo "ERROR:"
 	echo "$TAG_OUTPUT"
-	exit 1
+	unstash_changes
+	exit 6
 fi
 
 PUSH_OUTPUT="$(git push -q origin $TARGET_BRANCH --tags)"
 if [ $? != 0 ]; then
 	echo "ERROR:"
 	echo "TAG_OUTPUT"
-	exit 1
+	unstash_changes
+	exit 7
 fi
 
-if [ "$STASH_OUTPUT" != "No local changes to save" ]; then
-	POP_STASH="$(git stash pop)"
-	if [ $? != 0 ]; then
-		echo "ERROR:"
-		echo "$POP_STASH"
-		exit 1
-	fi
-fi
+unstash_changes
 
 exit 0
